### PR TITLE
Revert "CI: disable Python 3.10 and 3.11 tests"

### PR DESCRIPTION
**Pull request by stweil**
This reverts commit a5c72be47fb3c7d102565f3ff3983115527a491c.

### CODE REVIEW

**Comment by stweil** [comment]
Let's see whether CI still fails.

**Comment by stweil** [comment]
Hm, the CirrusCI obviously only runs on push, but not on a pull request. But PR #41 shows that ocrd_kraken works with all three Python releases.

**Comment by kba** [comment]
Merged into #42

**Comment by kba** [comment]
Still leads to core dump in at least 3.10 https://app.circleci.com/pipelines/github/OCR-D/ocrd_kraken/68/workflows/2ab8e003-721f-468e-9912-ae49c5a7e349/jobs/209 :(

**Comment by stweil** [comment]
libstdc++ throws a runtime error when accessing /dev/urandom:

```
#8  0x00007fff7b6a02bd in std::__throw_runtime_error(char const*) () from /lib/x86_64-linux-gnu/libstdc++.so.6
#9  0x00007fff7b6d38a3 in std::random_device::_M_getval() () from /lib/x86_64-linux-gnu/libstdc++.so.6
```

Here is another failing command:

```
echo | ocrd-kraken-recognize --dump-json
terminate called after throwing an instance of 'std::runtime_error'
  what():  random_device could not be read
Abgebrochen
```

**Comment by kba** [comment]
> libstdc++ throws a runtime error when accessing /dev/urandom:
> 
> ```
> #8  0x00007fff7b6a02bd in std::__throw_runtime_error(char const*) () from /lib/x86_64-linux-gnu/libstdc++.so.6
> #9  0x00007fff7b6d38a3 in std::random_device::_M_getval() () from /lib/x86_64-linux-gnu/libstdc++.so.6
> ```
> 
> Here is another failing command:
> 
> ```
> echo | ocrd-kraken-recognize --dump-json
> terminate called after throwing an instance of 'std::runtime_error'
>   what():  random_device could not be read
> Abgebrochen
> ```

Thanks for the debugging - how did you verify this? On a local machine or on Circle?

I don't see the same behavior with python 3.10 locally and the GH Action is working too, so I assume this is an issue with Circle's deployment conflicting with torch somehow.

I'll force-push the merge back from #42 and merge, so we can focus on the ocrd_all build.

**Comment by kba** [comment]
> @kba, note that there is an additional issue here. If `ocrd-kraken-recognize --dump-json` throws a runtime error, it wants to read from stdin before printing the error message. I think that's a bug, maybe in core.

What runtime error message does this throw for you?

**Comment by stweil** [comment]
See my previous comment. It throws std::runtime_error with the reason "random_device could not be read" from libstdc++.

**Comment by kba** [comment]
OK, thanks. The read from STDIN is particularly confusing. AFAIK the only place we do that in core is for `ocrd workspace bulk-add`. I will try to reproduce the issue and debug further with a Debian image, so let's keep the issue open. But in the interest of a timely ocrd_all release, I'll postpone that for now, as long as our docker containers work.

**Review by bertsky — APPROVED** [review]

**Pull request merged**
