### PR TITLE
Segment regions, incremental segmentation via masking

### LINKED ISSUE #23: segmentation: add optional level=region (line segmentation only)
According to the OCR-D functional model, line segmentation takes place after block segmentation. It should therefor check for existing text blocks and restrict its area of operation to them.

### PR DESCRIPTION
**Pull request by bertsky**
Fixes #23

### CODE REVIEW

**Review by kba — APPROVED** [review]
LGTM, more or less a full rewrite, thank you. Will test and then merge asap.

**Comment by bertsky** [comment]
@kba, have you done some tests already?

**Comment by bertsky** [comment]
I'm afraid with the [API changes in Kraken 5](https://github.com/mittagessen/kraken/releases/tag/5.2) we now have to adapt the OCR-D wrapper completely...

**Comment by bertsky** [comment]
> I'm afraid with the [API changes in Kraken 5](https://github.com/mittagessen/kraken/releases/tag/5.2) we now have to adapt the OCR-D wrapper completely...

done.

**Pull request merged**
